---
name: cmake swiss army knife
description: |
  Swiss army knife for projects based on cmake
branding:
  icon: 'compass'
  color: 'blue'
inputs:
  pre_command:
    description: 'Command to run at the start of the setup phase'
    default: ''
  dependencies_debian:
    description: 'Dependencies as Debian packages to install; used if defined'
    default: ''
  working-directory:
    description: 'cd to this directory; used if defined'
    default: ''
  cmakeflags:
    description: 'Initial flags for cmake; extended by presets'
    default: ''
  build_command:
    description: 'Build command to use; override presets'
    default: ''
  test_command:
    description: 'Test command to use; override presets'
    default: ''
  post_command:
    description: 'Command to run after tests; override presets'
    default: ''
  preset:
    description: |
      Preset to use:
      - cppcheck
      - iwyu
      - clang-tidy
      - clang-sanitize-*
      - gcc-sanitize-*
      - valgrind
      - coverage
      - install
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
