#!/bin/bash

function install_dependencies {
    if [ -n "$INPUT_DEPENDENCIES" ]; then
        su - -c "apt-get install --no-install-recommends -y $INPUT_DEPENDENCIES"
    fi
}

ctest=( ctest )
if [ -n "$INPUT_CTESTFLAGS" ]; then
    ctest+=( "$INPUT_CTESTFLAGS" )
fi

set -e -x

if [ -n "$INPUT_ANALYZER" ]; then
    if [ "$INPUT_ANALYZER" = "clang-tidy" ]; then
        install_dependencies
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
        find "$PWD" \( -name '*.[ch]' -o -name '*.cc' \) -exec clang-tidy -p "$PWD" {} +
    elif [ "$INPUT_ANALYZER" = "clang-format" ]; then
        find "$PWD" \( -name '*.[ch]' -o -name '*.cc' \) -exec clang-format -i {} +
        git diff --exit-code
    fi
else
    install_dependencies
    export CC="$INPUT_CC"
    export CFLAGS="$INPUT_CFLAGS"
    export CXXFLAGS="$INPUT_CXXFLAGS"

    SRCDIR="$PWD"
    mkdir /tmp/_build /tmp/_install
    cd /tmp/_build
    cmake -DCMAKE_INSTALL_PREFIX=/tmp/_install "$SRCDIR"
    make VERBOSE=1
    "${ctest[@]}"
    make install

    if [ -n "${INPUT_COVERAGE}" ]; then
        bash <(curl -s https://codecov.io/bash)
    fi
fi
